name: Deploy to GitHub Pages

on:
  push:
    branches: [ v2 ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      
      # New step: Install libvips for Sharp image processing
      - name: Install libvips
        run: sudo apt-get update && sudo apt-get install -y libvips42
      
      - name: Install, build, and upload your site
        uses: withastro/action@v2
        env:
          IMAGE_API_ACCESS_SECRET: ${{ secrets.IMAGE_API_ACCESS_SECRET }}
          IMAGE_API_ACCESS_KEY:  ${{ secrets.IMAGE_API_ACCESS_KEY }}
          IMAGE_API_REGION:  ${{ secrets.IMAGE_API_REGION }}
          IMAGE_API_BUCKET:  ${{ secrets.IMAGE_API_BUCKET }}
          IMAGE_API_URL:  ${{ secrets.IMAGE_API_URL }}
          IMAGE_CDN_URL:  ${{ secrets.IMAGE_CDN_URL }}
        with:
          path: .
          node-version: 18
          package-manager: pnpm@latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4